
name: fantastic

on:
  push:
    branches:
      - dojo
      
jobs:
  norminette:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  .
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install norminette
    - name: Lint with norminette
      run: |
        norminette
      working-directory: printf
  compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compiling with Makefile
        run: |
          pwd ;
          make
        working-directory: ../../ft_printf
